# Generated by Django 6.0.1 on 2026-06-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productvariant_delete_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Leave blank to show for all colours, or enter a colour name to show only when that colour is selected.', max_length=100),
        ),
    ]
