# Generated by Django 6.0.1 on 2026-06-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('shop_owner', 'Shop Owner')], default='shop_owner', max_length=20),
        ),
    ]
