# Generated by Django 6.0.1 on 2026-02-12 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
