# Generated by Django 6.0.1 on 2026-06-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
    ]
